env:
  LANG: C.UTF-8

test_task:
  container:
    image: elixir:latest
  mix_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script: mix local.hex --force && mix local.rebar --force && mix deps.get
  compile_script: mix local.hex --force && mix local.rebar --force && mix compile
  test_script: mix format && mix test
